// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZv_E3hFANsAhgN4DrhLtVm5SgMX2XzUo',
    appId: '1:912178167782:web:b0fe7370475685d27b2027',
    messagingSenderId: '912178167782',
    projectId: 'udhaar-kab-dega',
    authDomain: 'udhaar-kab-dega.firebaseapp.com',
    storageBucket: 'udhaar-kab-dega.appspot.com',
    measurementId: 'G-2YY29CEKND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IYVKokk42KkBJLkFFImqNECmqeZGRoY',
    appId: '1:912178167782:android:dd5dd90638c6d9267b2027',
    messagingSenderId: '912178167782',
    projectId: 'udhaar-kab-dega',
    storageBucket: 'udhaar-kab-dega.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG4E8-sTCk4VQsILe79Myyli_RgZ2N6f0',
    appId: '1:912178167782:ios:d80c3f84c1d82b1f7b2027',
    messagingSenderId: '912178167782',
    projectId: 'udhaar-kab-dega',
    storageBucket: 'udhaar-kab-dega.appspot.com',
    androidClientId:
        '912178167782-pkdfaa36u90qihr298s4elcggka9777e.apps.googleusercontent.com',
    iosClientId:
        '912178167782-sovce03uvec80b0bsm22ikp1la07qsq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.udhaarKabDega',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG4E8-sTCk4VQsILe79Myyli_RgZ2N6f0',
    appId: '1:912178167782:ios:144424cf2fc6c7247b2027',
    messagingSenderId: '912178167782',
    projectId: 'udhaar-kab-dega',
    storageBucket: 'udhaar-kab-dega.appspot.com',
    androidClientId:
        '912178167782-pkdfaa36u90qihr298s4elcggka9777e.apps.googleusercontent.com',
    iosClientId:
        '912178167782-jv8q18joif4jpguqkncm41qoo33b4oeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.udhaarKabDega.RunnerTests',
  );
}
